branch-defaults:
  default:
    environment: udagram-image-filter-dev
    group_suffix: null
global:
  application_name: udagram-image-filter
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: ./www/Archive.zip
